apiVersion: apps/v1
kind: Deployment
metadata:
  name: thisisscott
  namespace: thisisscott
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: thisisscott
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: thisisscott
    spec:
      containers:
      - image: harbor.192-168-2-19.nip.io/thisisscott/mypython:XXXXXX
        imagePullPolicy: Always
        name: thisisscott
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      imagePullSecrets:
      - name: pull-secret
      dnsPolicy: ClusterFirst
      imagePullSecret: pull-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30