apiVersion: v1
kind: Service
metadata:
  name: thisisscott
  namespace: thisisscott  # Specify the namespace
spec:
  selector:
    app: thisisscott  # Match pods with the label app=thisisscott
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the service
      targetPort: 8080  # Port on the container
  type: ClusterIP  # Default service type (accessible only within the cluster)
