kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admins-binding-internal
  namespace: "thisisscott"
subjects:
- kind: Group
  name: k8s-namespace-administrators-k8s-thisisscott-internal
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io